### ISSUE TITLE
when you becaome possessed you may be able to move with the effect

### ISSUE THREAD

**Issue by Yairb27** [MoonfaceDev/Heroes-of-the-Shrine#168] opened 2022-12-11 12:18 UTC
I will add more info when I will understand why it happen

**Comment by MoonfaceDev** [comment] 2022-12-11 22:21
Couldn't reproduce

**Comment by MoonfaceDev** [comment] 2022-12-12 21:46
thx
for now I assign you, reassign me when you have more info :)

**Closed** 2023-01-13 13:20 UTC
Labels: bug
